---
- name: Provision EC2 instance with Ansible
  hosts: ec2-lab-servers
  connection: local
  gather_facts: False

  vars:
    keypair: lab-ansible
    instance_type: t2.small
    image: ami-053b0d53c279acc90
    wait: yes
    count: 1
    region: us-east-1
    security_group: ansiblelabsg
  tasks:
    - name: Create Security Group
      ec2_group:
        name: "{{ security_group }}"
        description: Ansible deployment SG
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        tags:
          Name: my-security-group
    - name: Launch EC2 instance
      ec2:
        group={{ security_group }}
        instance_type={{ instance_type}}
        image={{ image }}
        wait=true
        region={{ region }}
        keypair={{ keypair }}
        count={{count}}
      register: ec2
    - name: Add tag for EC2 instance
      ec2_tag:
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: Deployment by Ansible
      with_items: "{{ ec2.instances }}"
